// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/skdiver33/gophkeeper/internal/datamanager (interfaces: DataStorage)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/skdiver33/gophkeeper/model"
)

// MockDataStorage is a mock of DataStorage interface.
type MockDataStorage struct {
	ctrl     *gomock.Controller
	recorder *MockDataStorageMockRecorder
}

// MockDataStorageMockRecorder is the mock recorder for MockDataStorage.
type MockDataStorageMockRecorder struct {
	mock *MockDataStorage
}

// NewMockDataStorage creates a new mock instance.
func NewMockDataStorage(ctrl *gomock.Controller) *MockDataStorage {
	mock := &MockDataStorage{ctrl: ctrl}
	mock.recorder = &MockDataStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataStorage) EXPECT() *MockDataStorageMockRecorder {
	return m.recorder
}

// DeleteData mocks base method.
func (m *MockDataStorage) DeleteData(arg0 context.Context, arg1 model.Metadata, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteData", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteData indicates an expected call of DeleteData.
func (mr *MockDataStorageMockRecorder) DeleteData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteData", reflect.TypeOf((*MockDataStorage)(nil).DeleteData), arg0, arg1, arg2)
}

// GetAllData mocks base method.
func (m *MockDataStorage) GetAllData(arg0 context.Context, arg1 int) (*[]model.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllData", arg0, arg1)
	ret0, _ := ret[0].(*[]model.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllData indicates an expected call of GetAllData.
func (mr *MockDataStorageMockRecorder) GetAllData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllData", reflect.TypeOf((*MockDataStorage)(nil).GetAllData), arg0, arg1)
}

// GetData mocks base method.
func (m *MockDataStorage) GetData(arg0 context.Context, arg1 model.Metadata, arg2 int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData", arg0, arg1, arg2)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetData indicates an expected call of GetData.
func (mr *MockDataStorageMockRecorder) GetData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockDataStorage)(nil).GetData), arg0, arg1, arg2)
}

// GetMetaData mocks base method.
func (m *MockDataStorage) GetMetaData(arg0 context.Context, arg1 string, arg2 int) (*model.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetaData", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetaData indicates an expected call of GetMetaData.
func (mr *MockDataStorageMockRecorder) GetMetaData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetaData", reflect.TypeOf((*MockDataStorage)(nil).GetMetaData), arg0, arg1, arg2)
}

// InsertData mocks base method.
func (m *MockDataStorage) InsertData(arg0 context.Context, arg1 model.Metadata, arg2 []byte, arg3 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertData", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertData indicates an expected call of InsertData.
func (mr *MockDataStorageMockRecorder) InsertData(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertData", reflect.TypeOf((*MockDataStorage)(nil).InsertData), arg0, arg1, arg2, arg3)
}
