// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/skdiver33/gophkeeper/internal/usermanager (interfaces: UserStorageInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/skdiver33/gophkeeper/model"
)

// MockUserStorageInterface is a mock of UserStorageInterface interface.
type MockUserStorageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserStorageInterfaceMockRecorder
}

// MockUserStorageInterfaceMockRecorder is the mock recorder for MockUserStorageInterface.
type MockUserStorageInterfaceMockRecorder struct {
	mock *MockUserStorageInterface
}

// NewMockUserStorageInterface creates a new mock instance.
func NewMockUserStorageInterface(ctrl *gomock.Controller) *MockUserStorageInterface {
	mock := &MockUserStorageInterface{ctrl: ctrl}
	mock.recorder = &MockUserStorageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStorageInterface) EXPECT() *MockUserStorageInterfaceMockRecorder {
	return m.recorder
}

// AddUser mocks base method.
func (m *MockUserStorageInterface) AddUser(arg0 context.Context, arg1 *model.User) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUser indicates an expected call of AddUser.
func (mr *MockUserStorageInterfaceMockRecorder) AddUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockUserStorageInterface)(nil).AddUser), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockUserStorageInterface) GetUser(arg0 context.Context, arg1, arg2 string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserStorageInterfaceMockRecorder) GetUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserStorageInterface)(nil).GetUser), arg0, arg1, arg2)
}
